### ISSUE TITLE
配置好后运行出错

### ISSUE THREAD

**Issue by Anran0205** [Youthux/piaoxingqiu#1]
Traceback (most recent call last):
  File "F:\chrome download\piaoxingqiu-main\main.py", line 1, in <module>
    import request
  File "F:\chrome download\piaoxingqiu-main\request.py", line 8, in <module>
    def get_sessions(show_id) -> list | None:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

**Comment by Youthux** [comment]
> Traceback (most recent call last): File "F:\chrome download\piaoxingqiu-main\main.py", line 1, in import request File "F:\chrome download\piaoxingqiu-main\request.py", line 8, in def get_sessions(show_id) -> list | None: TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

是不是python版本的问题，我是3.10版本

**Comment by Youthux** [comment]
> 您好，your_token里填写什么，账号名称还是令牌，令牌怎么获得？

readme更新了，看下readme

**Comment by ConquerBJ** [comment]
我和一楼是同样的问题：TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

Python版本：Python 3.8.16 (default, Jan 17 2023, 16:42:09)

**Comment by wushal-117** [comment]
> 我和一楼是同样的问题：TypeError： |： 'type' 和 'NoneType' 的不支持的操作数类型（s）
> 
> Python版本：Python 3.8.16（默认，17年2023月16日，42：09：<>）

我也是
def get_sessions(show_id) -> list | None:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

**Comment by Youthux** [comment]
对代码已做调整，应该可以了
