### ISSUE TITLE
大佬，拉了新代码之后报模块错误了，我的python版本是3.10.10

### ISSUE THREAD

**Issue by yuhengZheng1229** [Youthux/piaoxingqiu#5]
Traceback (most recent call last):
  File "D:\piaoxingqiu\main.py", line 3, in <module>
    from apscheduler.schedulers.blocking import BlockingScheduler
ModuleNotFoundError: No module named 'apscheduler'

**Comment by Youthux** [comment]
> Traceback (most recent call last): File "D:\piaoxingqiu\main.py", line 3, in from apscheduler.schedulers.blocking import BlockingScheduler ModuleNotFoundError: No module named 'apscheduler'

命令行执行pip install -r requirements.txt，参考readme
